kind: pipeline
name: default

steps:
- name: check-mongo
  image: mongo:4
  commands:
  - sleep 5
  - mongo --host mongo --eval "db.version()"

- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment:
    MONGO_ADDRESS: mongo
  commands:
  - cd src
  - dotnet build Horarium.sln -c Release
  - dotnet test Horarium.Test/Horarium.Test.csproj --no-restore
  - dotnet test Horarium.IntegrationTest/Horarium.IntegrationTest.csproj --no-restore 
  when:
    event:
    - push
    branch:
    - master

- name: push
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment:
    NUGET_APIKEY: 
      from_secret: NUGET_APIKEY
  commands:
  - cd src
  - dotnet pack Horarium/Horarium.csproj -c Release --no-build  /p:PackageVersion=$DRONE_TAG
  - dotnet nuget push **/Horarium.*.nupkg -k $NUGET_APIKEY
  when:
    event:
    - tag
    branch:
    - master


services:
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
  - 27017
