kind: pipeline
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
  - cd src
  - dotnet build Horarium.sln -c Release
  - dotnet test Horarium.Test/Horarium.Test.csproj --no-restore
  when:
    event:
    - push
    branch:
    - master

  